@startuml
participant 上位机
participant MasterNode
participant SlaveNode
participant ConductionPins
participant ResistancePins
participant ClipDevice
== Devices Query ==
上位机 -> MasterNode : 发送设备查询指令
MasterNode -> SlaveNode : Read Clip Info Message
SlaveNode -> ClipDevice : Clip.ReadNum()
ClipDevice -> SlaveNode : ClipNum
SlaveNode --> MasterNode : Clip Info Message
alt 指令超时（下同）
    上位机 -> 上位机 : 记录超时错误
    上位机 -> MasterNode : 重新发送设备查询指令（最多3次）
    alt 超时重试3次仍失败
        上位机 -> 上位机 : 触发异常处理
    else 成功收到回复
        MasterNode --> 上位机 : 设备设备查询回复
    end
else 正常响应
    MasterNode --> 上位机 : 设备查询指令回复
end

== Devices Config ==
上位机 -> MasterNode : 发送设备配置指令
alt 指令超时（下同）
    上位机 -> 上位机 : 记录超时错误
    上位机 -> MasterNode : 重新发送设备配置指令（最多3次）
    alt 超时重试3次仍失败
        上位机 -> 上位机 : 触发异常处理
    else 成功收到回复
        MasterNode --> 上位机 : 设备配置指令回复
    end
else 正常响应
    MasterNode --> 上位机 : 设备配置指令回复
end

== Conduction Test ==
上位机 -> MasterNode : 发送模式选择指令（导通检测）
MasterNode --> 上位机 : 模式选择指令回复
MasterNode -> SlaveNode : Write Conduction Info Message
SlaveNode --> MasterNode : Conduction Info Message

上位机 -> MasterNode : 发送设备控制指令（开）
MasterNode --> 上位机 : 设备控制指令回复

loop 导通数据传输
    MasterNode -> SlaveNode : Sync Message

    loop for each SlaveNode from 0 to n

    loop for each pin from 0 to 61
        SlaveNode -> ConductionPins: conduction.read(pin)
        ConductionPins --> SlaveNode: Pin Level
    end

        MasterNode -> SlaveNode : Read Conduction Data Message
        SlaveNode --> MasterNode : Conduction Data Message
        MasterNode -> 上位机 : 发送导通检测数据
    end
    
    上位机 -> 上位机 : 判断数据是否足够
end

上位机 -> MasterNode : 发送设备控制指令（关）
MasterNode --> 上位机 : 设备控制指令回复

== Resistance Test ==
上位机 -> MasterNode : 发送模式选择指令（阻值检测）
MasterNode --> 上位机 : 模式选择指令回复
MasterNode -> SlaveNode : Write Resistance Info Message
SlaveNode --> MasterNode : Resistance Info Message
上位机 -> MasterNode : 发送设备控制指令（开）
MasterNode --> 上位机 : 设备控制指令回复

loop 阻值数据传输
    MasterNode -> SlaveNode : Sync Message

    loop for each SlaveNode from 0 to n

    loop for each pin from 0 to 61
        SlaveNode -> ResistancePins: Resistance.read(pin)
        ResistancePins --> SlaveNode: Resistance Data
    end

        MasterNode -> SlaveNode : Read Resistance Data Message
        SlaveNode --> MasterNode : Resistance Data Message
        MasterNode -> 上位机 : 发送阻值检测数据
    end
    
    上位机 -> 上位机 : 判断数据是否足够
end

上位机 -> MasterNode : 发送设备控制指令（关）
MasterNode --> 上位机 : 设备控制指令回复

== Clip Test ==
上位机 -> MasterNode : 发送模式选择指令（ClipDevice检测）
MasterNode --> 上位机 : 模式选择指令回复
MasterNode -> SlaveNode : Write Clip Info Message
SlaveNode --> MasterNode : Clip Info Message
上位机 -> MasterNode : 发送设备控制指令（开）
MasterNode --> 上位机 : 设备控制指令回复

loop ClipDevice数据传输

    MasterNode -> SlaveNode : Sync Message

    loop for each SlaveNode from 0 to n

    loop for each clip from 0 to n
        SlaveNode -> ClipDevice : Clip.Read()
        ClipDevice -> SlaveNode: ClipData
    end

        MasterNode -> SlaveNode : Read Clip Data Message
        SlaveNode --> MasterNode : Clip Data Message
        MasterNode -> 上位机 : 发送ClipDevice检测数据
    end

    上位机 -> 上位机 : 判断数据是否足够

end

上位机 -> MasterNode : 发送设备控制指令（关）
MasterNode --> 上位机 : 设备控制指令回复

== Devices Reset ==
上位机 -> MasterNode : 发送解锁指令
MasterNode --> 上位机 : 解锁指令回复
MasterNode -> SlaveNode : Lock Message
SlaveNode -> SlaveNode : Lock 
SlaveNode --> MasterNode : Lock Status Message

@enduml
